from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 600)
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        #sizePolicy.setHorizontalStretch(0)
        #sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        #MainWindow.setSizePolicy(sizePolicy)
        self.main_text = QtWidgets.QLabel(self)  # текстовая надпись, в окне window
        self.main_text.setText('Основная надпись')  # сам текст внутри надписи
        self.main_text.move(100, 50)
        # передвинуть надпись на 100 вправо и 50 вниз от окна
        self.main_text.adjustSize()

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tab = QtWidgets.QTableWidget(self.centralwidget)
        self.tab.setEnabled(True)
        self.tab.setGeometry(QtCore.QRect(50, 50, 451, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMinimumSize(QtCore.QSize(100, 200))
        self.tab.setMouseTracking(False)
        self.tab.setAcceptDrops(False)
        self.tab.setAutoFillBackground(False)
        self.tab.setLineWidth(1)
        self.tab.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tab.setAutoScroll(True)
        self.tab.setProperty("showDropIndicator", True)
        self.tab.setAlternatingRowColors(False)
        self.tab.setShowGrid(True)
        self.tab.setWordWrap(True)
        self.tab.setCornerButtonEnabled(True)
        self.tab.setObjectName("tab")
        self.tab.setColumnCount(5)
        self.tab.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setHorizontalHeaderItem(4, item)
        self.tab.horizontalHeader().setVisible(False)
        self.tab.horizontalHeader().setDefaultSectionSize(89)
        self.tab.horizontalHeader().setStretchLastSection(True)
        self.tab.verticalHeader().setVisible(False)
        self.tab.verticalHeader().setDefaultSectionSize(57)
        self.tab.verticalHeader().setStretchLastSection(True)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 470, 485, 64))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.b_settings = QtWidgets.QPushButton(self.splitter)
        self.b_settings.setObjectName("b_settings")
        self.b_statistics = QtWidgets.QPushButton(self.splitter)
        self.b_statistics.setObjectName("b_statistics")
        self.horizontalLayout.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.splitter_2 = QtWidgets.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.b_play = QtWidgets.QPushButton(self.splitter_2)
        self.b_play.setObjectName("b_play")
        self.b_close = QtWidgets.QPushButton(self.splitter_2)
        self.b_close.setObjectName("b_close")
        self.horizontalLayout.addWidget(self.splitter_2)
        spacerItem1 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.b_input = QtWidgets.QPushButton(self.splitter_3)
        self.b_input.setObjectName("b_input")
        self.b_erase = QtWidgets.QPushButton(self.splitter_3)
        self.b_erase.setObjectName("b_erase")
        self.horizontalLayout.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Игра 5БУКВ"))
        self.label.setText(_translate("MainWindow", "Загаданое слово"))
        self.tab.setSortingEnabled(False)
        item = self.tab.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tab.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tab.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tab.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tab.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tab.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tab.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "5"))
        item = self.tab.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tab.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "У"))
        item = self.tab.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "К"))
        item = self.tab.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "В"))
        self.b_settings.setText(_translate("MainWindow", "Настройки"))
        self.b_statistics.setText(_translate("MainWindow", "Статистика"))
        self.b_play.setText(_translate("MainWindow", "Иргать"))
        self.b_close.setText(_translate("MainWindow", "Закрыть"))
        self.b_input.setText(_translate("MainWindow", "Ввод"))
        self.b_erase.setText(_translate("MainWindow", "Стереть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
